### ISSUE TITLE
Should disable_NMEA call take ~5min to complete ?

### ISSUE THREAD

**Issue by gzamb** [Korving-F/ublox#5]
I'm using this call since I only want to get UBX protocol messages at a high rate (5 times a second).  I've noticed though that the higher my baudrate that the longer this call takes, sometimes not even completing.  When I drilled down into the call, I kept getting a long wait or error when trying to disable 0xF0 0x42.....as soon as I took that out from the list it worked consistently.  Is there any reason why this call would fail or take so long compare to the other ones?

**Comment by Korving-F** [comment]
I personally have never had any issues; it's a little strange that it takes that long because the confirmation message read should timeout after 5 seconds. In any case, some of these messages don't need an explicit disable call anyways since they are one-off polling or config  messages (I naively just sent UBX CFG messages for all defined NMEA class/id combinations by the looks of it.).

I removed the redundant messages from the script; thanks for pointing that out ^_^ I hope it's working fine next to that.

**Comment by Korving-F** [comment]
Closing this issue due to it seeming to blocking issue seeming to have disappeared.
Thanks :)
