### ISSUE TITLE
aproblem

### ISSUE THREAD

**Issue by yuanshuai19960730** [Korving-F/ublox#9]
hello,here is my problem :
i follow the usage describle in the usage.png
nav_posllh = x.read()
No errors have been found as of now
and then when i go next 
nav_posllh.lat
 it says that nav_posllh has no attribute 'lat'
nav_posllh.l 
it says that nav_posllh has no attribute 'l'
could u help me with that ,thanks

**Comment by Korving-F** [comment]
Hi; I can try ^_^

Can you send me your entire code snippet as you write it?
Can you also try the following and send the resulting output? 
```python
y = x.read()
print(y.ubx_id)
print(y.ubx_class)
```
Which version of python are you using?

**Comment by yuanshuai19960730** [comment]
![image](https://user-images.githubusercontent.com/68501201/88245502-05251d80-ccca-11ea-984c-478a0b3728a9.png)
Thanks for your reply:
  Can you see the picture i send,my code snippet is on it 
  I had tried y.ubx_id ,it says 'UbxMessage' object has no attribute 'ubx_id'
  The vision of python is Python 3.6.9  on Ubuntu system.
Look forward to your reply,thanks

**Comment by Korving-F** [comment]
I think I can see what the problem is: you're enabling NAV-POSLLH to be sent regularly.
But other messages have been enabled on your GPS module as well (many are not supported as of this moment).
At the moment the script fails silently if it receives unsupported messages.

```python
>>> y = x.read()
Receiving
02 14  # <- This is a class 2, id 14 event you are receiving: UBX-RXM-MEASX not NAV-POSLLH
```

There are multiple things you can/should do:

- Disable the event and any others you're not interested in:
```python
x.disable_message(2,20) # Note that it prints out the class/id in hexadecimal, but takes in these as integers
```
- Read safely and possibly without a flush (untested code; may contain a typo):
```python
while(True):
    try:
        y = x.read()
        if(y.ubx_id == '02' and y.ubx_class == '01'):
            print("You found a NAV-POSLLH message ^_^")
            print(y.lat)
        else:
            print("You found a different but supported message.")
            print("ID: " + y.ubx_id + " Class: " + y.ubx_class)
            print("Variables: " + vars(y))
    except:
        print("Now you found an unsupported message")
```

See this document for more message types and technical information on the receiver: https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf

If you find a message you want to have added let me know :)

**Comment by yuanshuai19960730** [comment]
![image](https://user-images.githubusercontent.com/68501201/88374322-266e3280-cdcc-11ea-9a04-1f77dd393175.png)
thanks a lot ,i had received some message illustrated as the up picture
but ,there is still a problem:
i only enable two kinds message POSLLH(01,02)  and PVT(01,07) on u-center on my computer 
![image](https://user-images.githubusercontent.com/68501201/88375953-14da5a00-cdcf-11ea-899e-019db25268a5.png)
and then i do as follow:
>>>x.disable_message(1,7)
>>>.xenable_message(1,7)
![image](https://user-images.githubusercontent.com/68501201/88376801-b7470d00-cdd0-11ea-9cc9-4b50d33c780e.png)
does it means i cannot enable message use the code but only can enable message use u-center?because PVT turn gray on u-center
![image](https://user-images.githubusercontent.com/68501201/88376967-fffec600-cdd0-11ea-914d-6b6d46fc6a63.png)

**Comment by Korving-F** [comment]
I'm not sure what exactly the issue is for you; it seems to work. Some things maybe you can try:
- Set the baudrate to 9600
- Disable all NMEA messages if you don't need them:
```python
x.disable_NMEA() # get rid of noise
```
- try multiple executions of x.enable_message(1,7). 

When it enables a message type a CFG message is sent and only when the receiver processes this correctly an ACK is sent. If the message is sent but is malformed/not supported etc. it will send a NACK. In your case it seems to receive neither.

Let me know how your experiments are going; hope I can be of more help ^_^

**Comment by yuanshuai19960730** [comment]
i have tried , i can only disable_message here.
I have set on u-center that i can only receive 01,07 and 01,02 ,and after i disable_message(01,07)
i cannot receive 01,02 message either,it syas 
![image](https://user-images.githubusercontent.com/68501201/88446564-a7293f00-ce5d-11ea-8db3-c51aaec0af0a.png)
i think i can only enable/disable message on u-center now,and that does not matter.

and here i have a much more imortant question ,when i receive 01,02 message, it works well
![image](https://user-images.githubusercontent.com/68501201/88446609-16069800-ce5e-11ea-87ea-8c6d19c84787.png)

but when i receive a 01,07 message
![image](https://user-images.githubusercontent.com/68501201/88446613-20289680-ce5e-11ea-9b75-afae223e1948.png)
i just cannot understanding it!!
wish u can help me with that😂

**Comment by Korving-F** [comment]
Hmm; this seems like a classical python2 vs. 3 error.
Can you stop sending all messages in u-center and send back a similar image as below?

btw; do you have pyserial properly installed? 
```console
pip install --upgrade --force-reinstall pyserial
pip3 install --upgrade --force-reinstall pyserial
```

Also which version of this project are you using? (maybe do a pull / clean clone? just in case)

![image](https://user-images.githubusercontent.com/17042203/88450763-038a5f80-ce5a-11ea-9c5f-53221b26817d.png)

![image](https://user-images.githubusercontent.com/17042203/88450983-f2dae900-ce5b-11ea-8da9-4b46cee6b057.png)

**Comment by yuanshuai19960730** [comment]
![image](https://user-images.githubusercontent.com/68501201/88455281-b680aa80-cea6-11ea-9061-45fa9051f3a2.png)
i  stopped all information and did pip3 install --upgrade --force-reinstall pyserial.
the only difference is my pyserial is in dir /.local/lib/python3.6/site-packages and yours is  in dir usr/loacl/lib/python3.6/dist-packages.
does it matter? I'm not familiar with Python on linux.Because i have this mission ,i have to learn about it .

my project is python 3.6.9,i did not install python 2.x
![image](https://user-images.githubusercontent.com/68501201/88455412-a0271e80-cea7-11ea-90e0-7372fe119ae5.png)

and In the same case,message 01,02 works well ,but 01,07 just has problem ,it is really Weird !!
my mother language is not english ,and i cannot understand the meaning  of  "do a pull / clean clone",sorry about that😭
BTW,you reply to me so early today ,i guess you must  have a holiday today😁.Wish you have a good time!

**Comment by Korving-F** [comment]
You're probably doing the installation correct; the way I installed the package on my system is actually insecure and should be avoided. Although you could look into using venv virtual environment.

Could you try to print PATH as described here just in case?: https://www.dummies.com/programming/python/how-to-find-path-information-in-python/ 

If you don't see your .local dir printed there follow for example PYTHONPATH example to add it manually: https://www.devdungeon.com/content/python-import-syspath-and-pythonpath-tutorial

Git pull / git clone:
```console
cd ~/Desktop/py/
git clone https://github.com/Korving-F/ublox
# https://docs.github.com/en/enterprise/2.13/user/articles/cloning-a-repository
```
Can you also send a "ls -lah /dev/ttyACM3"?
It might be that running in a VM is complicating things.

Doing this from my phone so sorry for the incomplete response. Really not sure what it otherwise could be..

P.s. your English is good ^_^

**Comment by yuanshuai19960730** [comment]
i am so happy that the question is solved:
i just git pull/git clone and it works well now
![image](https://user-images.githubusercontent.com/68501201/88469620-208c6480-cf26-11ea-9ad0-9dacd0b452b2.png)
however, the enable/disable still does not work.but i can continue my work now：to add some message that i need like you do in the code .
BTW,i noticed that my ublox is version f9p,maybe this is the reason?
You are such a warmhearted and nice man,Wish everything goes well with you☺.Thank you very much!!

**Comment by Korving-F** [comment]
Awesome :D no worries and good luck with your project!
I'll try to look at f9p; maybe something changed :)
Greetings!
